# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a028ed59f33a2fb5e96fa35dbb7c0fdf4bfc881d535c91505f6e2373d587a0b04be69f5f7332796b0bdce128f74d74989e62d951a1850ff8811cd8ea99c22c0a

test:
  secret_key_base: f3dc5e18bf2c5673301fe566fcef9558553dd15230f9e2b28aa44d6738084cb0ac5362f71bcdb39d8d9403ab5412b051de70a85ea6f4844f971dafabc5b5c1c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
